name: Rust

on:
    pull_request:
        types:
            - opened
            - reopened
    push:

jobs:
    cobitis:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./
        steps:
            - name: Checkout Crate
              uses: actions/checkout@v4
            - name: Set Toolchain
              uses: dtolnay/rust-toolchain@stable
            - name: Install aarch64 target
              run: rustup target add aarch64-unknown-linux-gnu
            - name: Install clippy
              run: rustup component add clippy
            - name: cargo clippy
              run: cargo clippy
